[env:esp32-s3-devkitc-1]

platform_packages = espressif/toolchain-riscv32-esp@8.4.0+2021r2-patch5
platform = espressif32
;platform = espressif32 @ 4.4.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_port = /dev/cu.usbmodem14*
monitor_speed = 115200
upload_speed = 9600
monitor_rts = 0
monitor_dtr = 0
monitor_filters =
      -time
      -default
; build_flags =
;     -Werror
;     -pedantic-errors
;     -Wall
;     -Wextra
;     -Wpedantic
;     -Wcast-align
;     -Wcast-qual
;     -Wconversion
;     -Wctor-dtor-privacy
;     -Wduplicated-branches
;     -Wduplicated-cond
;     -Wextra-semi
;     -Wfloat-equal
;     -Wlogical-op
;     -Wnon-virtual-dtor
;     -Wold-style-cast
;     -Woverloaded-virtual
;     -Wredundant-decls
;     -Wsign-conversion
;     -Wsign-promo 

; check_skip_packages = yes
; check_skip_framework = yes
